name: Tests (Jest & esLint)

on:
  push:
  
jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: npm install
      run: npm install

    - name: run eslint
      run: npm run lint -- -f junit -o lint-junit.xml

  # jest:
  #   name: Jest Test
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '16.x'

  #   - name: npm login
  #     run:
  #       echo "//gitlab.com/api/v4/projects/27178462/packages/npm/:_authToken=$GITLAB_PACKAGES_TOKEN" >> ~/.npmrc &&
  #       echo "@b4-org:registry=https://gitlab.com/api/v4/projects/27178462/packages/npm/" >> ~/.npmrc
  #     env:
  #       GITLAB_PACKAGES_TOKEN: ${{ secrets.GITLAB_PACKAGES_TOKEN }}

  #   - name: npm install
  #     run: npm install

  #   - name: run jest
  #     run: npx jest --ci --reporters=default --reporters=jest-junit

  #   - name: Jest Report
  #     uses: dorny/test-reporter@v1.5.0
  #     if: success() || failure()
  #     with:
  #       name: Jest Report
  #       path: reports/jest-*.xml
  #       reporter: jest-junit
